### PR TITLE
Add script to find case information

### PR DESCRIPTION
**Pull request by bschoenfeld**
This script scrapes Virginia’s District Court case information system in an effort to deanonymize the case data in the cases directory.

It works by using the case information system’s hearing date search to look for all cases that were finalized on the anonymous case’s `FINAL_DISP_DATE` field. It then loads the details page for each case found. If the case shares `CASE_TYPE`, `FILE_DATE`, and `OFFENSE_CLASS_CODE`, it is considered a match for the anonymous case.

All matches are written to a new CSV file that looks just like the original with `CASE_NUMBER` and `NAME` fields added.

### CODE REVIEW

**Comment by bschoenfeld** [comment]
This script takes a while to run. Typically a few minutes per case. Here is the first bit of data I got from it. Let's verify that the data is good and the script is working correctly before the pull request is accepted.

```
FIPS,CASE_TYPE,ATTORNEY_TYPE,FILE_DATE,OFFENSE_CLASS_CODE,FINAL_DISP_DATE,CASE_NUMBER,NAME,MATCH
3,F,N,3/31/14,6,3/31/14,GC14003789-00,"RITTENHOUSE, AARON W.",1
9,F,N,2/24/14,O,4/3/14,GC14001574-00,"RAGLAND, ANTHONY WAYNE",1
11,F,N,5/29/14,5,7/30/14,GC14001544-00,"SANGIACOMO, MARY LOUISE",1
13,F,N,3/4/13,6,6/10/14,GC13000993-00,"LYONS, JONATHAN",1
13,F,N,10/7/13,5,5/2/14,,,
13,F,N,12/12/13,O,1/23/14,GC13005828-00,"JONES, DEMONTE ANTHONY",1
13,F,N,12/23/13,U,1/10/14,GC13005964-00,"BROWN, CORNELL ROBERT",1
13,F,N,12/23/13,6,4/17/14,GC13005979-00,"DEVITO PISCICELLI, DANTE",1
13,F,N,12/23/13,6,4/17/14,GC13005974-00,"OBERHEIM, ADAM DOUGLAS",2
13,F,N,12/23/13,6,4/17/14,GC13005975-00,"OBERHEIM, ADAM DOUGLAS",3
13,F,N,12/23/13,6,4/17/14,GC13005980-00,"OBERHEIM, ADAM DOUGLAS",4
13,F,N,12/23/13,6,4/17/14,GC13005979-00,"DEVITO PISCICELLI, DANTE",1
13,F,N,12/23/13,6,4/17/14,GC13005974-00,"OBERHEIM, ADAM DOUGLAS",2
13,F,N,12/23/13,6,4/17/14,GC13005975-00,"OBERHEIM, ADAM DOUGLAS",3
13,F,N,12/23/13,6,4/17/14,GC13005980-00,"OBERHEIM, ADAM DOUGLAS",4
13,F,N,12/23/13,6,4/17/14,GC13005979-00,"DEVITO PISCICELLI, DANTE",1
13,F,N,12/23/13,6,4/17/14,GC13005974-00,"OBERHEIM, ADAM DOUGLAS",2
13,F,N,12/23/13,6,4/17/14,GC13005975-00,"OBERHEIM, ADAM DOUGLAS",3
13,F,N,12/23/13,6,4/17/14,GC13005980-00,"OBERHEIM, ADAM DOUGLAS",4
13,F,N,1/2/14,2,1/2/14,GC13006123-00,"LINK, JAMES THOMAS",1
13,F,N,1/2/14,2,1/2/14,GC13006138-00,"MCNEAL, JAMES LARRY",2
13,F,N,1/2/14,2,1/2/14,GC13006124-00,"STODDARD, ALFONSO",3
13,F,N,1/2/14,2,1/2/14,GC13006123-00,"LINK, JAMES THOMAS",1
13,F,N,1/2/14,2,1/2/14,GC13006138-00,"MCNEAL, JAMES LARRY",2
13,F,N,1/2/14,2,1/2/14,GC13006124-00,"STODDARD, ALFONSO",3
13,F,N,1/2/14,2,1/2/14,GC13006123-00,"LINK, JAMES THOMAS",1
13,F,N,1/2/14,2,1/2/14,GC13006138-00,"MCNEAL, JAMES LARRY",2
13,F,N,1/2/14,2,1/2/14,GC13006124-00,"STODDARD, ALFONSO",3
13,F,N,1/27/14,U,2/3/14,GC14000325-00,"GILMARTIN, LAWRENCE PATRICK",1
13,F,N,2/21/14,U,3/4/14,GC14000716-00,"MORRISON, CHARMECE NICOLE",1
13,F,N,3/4/14,U,3/11/14,GC14000841-00,"HICKMAN, ERIC DEWAYNE",1
```

**Comment by bschoenfeld** [comment]
I'm also wondering if we want to post the results to the repo or leave them out to keep the data publicly anonymous.

**Comment by fj** [comment]
> This script takes a while to run. Typically a few minutes per case.

Is that accurate?! If so, it's going to take a really long time to get every case in, then. For example if there are 10,000 cases and each case takes 3 minutes to load, then it will take three weeks of nonstop crunching to get every case downloaded.

**Comment by bschoenfeld** [comment]
@fj Yep. It's accurate. Smaller courts finish in just a few seconds, but the larger courts take a while. They can hear hundreds of cases in a day. We have to make a request to the server for each case that gets finalized and we have to rate limit our requests to one a second or the system locks us out. Luckily, there are less than 2,000 cases in the data in this repo. We should be able to get that done in a couple days. And the script only needs to run once a year.

**Comment by waldoj** [comment]
I accepted the pull request despite not knowing if the script is working properly because I like to live dangerously. ;)

I'm going to give this a whirl!

**Comment by waldoj** [comment]
I got an immediate error:

```
Partial case 1 of 486
    Searching Albemarle General District Court for cases on 03/31/2014
Traceback (most recent call last):
  File "./process-cases.py", line 94, in <module>
    cases = reader.get_cases_by_date(fips_code, search_date)
  File "~/attorney-analysis-master/courtreader/readers.py", line 34, in get_cases_by_date
    cases.extend(districtcourtparser.parse_hearing_date_search(soup))
  File "~/attorney-analysis-master/courtreader/districtcourtparser.py", line 24, in parse_hearing_date_search
    'status': list(cells[6].stripped_strings)[0]
IndexError: list index out of range
```

I assume that means that the HTML doesn't match what is expected.

**Comment by bschoenfeld** [comment]
Yeah. That's strange. Let me add some better debug stuff so I can't take a
look at your issue.

**Comment by bschoenfeld** [comment]
Just submitted #5. Give that a try. I fixed one thing in the parser, but I doubt it will fix your problem. If you get the exception again, send me the `unexcepted_output.html` file and the stack trace (if its any different).

**Comment by waldoj** [comment]
Stack trace is the same. Here's the output.

https://gist.github.com/waldoj/1e8c71003c5546875235

**Comment by waldoj** [comment]
Ah, now it's working better. :)

**Comment by waldoj** [comment]
These results certainly look good to me!

``` csv
FIPS,CASE_TYPE,ATTORNEY_TYPE,FILE_DATE,OFFENSE_CLASS_CODE,FINAL_DISP_DATE,CASE_NUMBER,NAME,MATCH
3,F,N,3/31/14,6,3/31/14,GC14003789-00,"RITTENHOUSE, AARON W.",1
9,F,N,2/24/14,O,4/3/14,GC14001574-00,"RAGLAND, ANTHONY WAYNE",1
11,F,N,5/29/14,5,7/30/14,GC14001544-00,"SANGIACOMO, MARY LOUISE",1
13,F,N,3/4/13,6,6/10/14,GC13000993-00,"LYONS, JONATHAN",1
```

**Comment by fj** [comment]
What does it look like for a case with no attorney?

**Comment by rpogge** [comment]
You've done it! I can't thank you gentlemen enough. Let me know when you can send me a complete list.

**Comment by waldoj** [comment]
> What does it look like for a case with no attorney?

In the HTML, it's just a blank cell. I assume @bschoenfeld is detecting those to output the `N` value for an attorney.

Ben, do you have this running somewhere, or should I fire up an EC2 Micro instance and leave it running for a few days? :)

**Comment by fj** [comment]
Rad; once you get the other half of this data I'll be happy to finish things up in #1!

**Comment by bschoenfeld** [comment]
> What does it look like for a case with no attorney?

@fj @waldoj I'm not doing anything with the attorney field. It's always `N` in data in this repo and I see a field on the case information site for attorney, but I've never seen anything in it. Should I be doing something with it? I don't understand the original question.

@waldoj Because the site tends to kick me out every night (and sometimes during the day), I usually just run locally so I can keep an eye on it. I've got about 20% of 2014 done. You can try to do another year on EC2 - you have to change the date in the script [here](https://github.com/openva/attorney-analysis/blob/master/process-cases.py#L65).

**Comment by waldoj** [comment]
Great—I'm running 2013 now.

**Comment by waldoj** [comment]
84 of 322 cases matched.

**Comment by waldoj** [comment]
248 of 322 cases matched.

**Comment by bschoenfeld** [comment]
Done with 2014. Starting 2012.

**Pull request merged**
